name: typescript / format

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: 'Verify formatting of all files'
        run: ./bin/check-formatting.sh
        env:
          EXERCISM_PRETTIER_VERSION: '2.2.1'
