name: typescript / format

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.3.4

      - name: 'Verify formatting of all files'
        run: ./bin/check-formatting.sh
        env:
          EXERCISM_PRETTIER_VERSION: '2.2.1'
