name: typescript / format

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.3.4

      - name: 'Verify formatting of all files'
        run: ./bin/check-formatting.sh
        env:
          EXERCISM_PRETTIER_VERSION: '2.2.1'
